/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-07-30 06:11:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("request.getSchema()可以返回当前页面使用的协议，http 或是 https;\r\n");
      out.write("request.getServerName()可以返回当前页面所在的服务器的名字;\r\n");
      out.write("request.getServerPort()可以返回当前页面所在的服务器使用的端口,就是80;\r\n");
      out.write("request.getContextPath()可以返回当前页面所在的应用的名字;\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd \r\n");
      out.write("\r\n");
      out.write(" \">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- base标签是一个基本链接标记，网页上的所有相对路径在链接时都将在前面加上基链接指向的地址 -->\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<title>后台主页面</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\twidth: 1300px;\r\n");
      out.write("\tborder: 1px solid #006633;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("\twidth: 1300px;\r\n");
      out.write("\tbackground-image: url(images/admin/bb1.jpg);\r\n");
      out.write("\tmargin: 0px 0px 3px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header h1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-family: 楷体;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\tfont-size: 50px；\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator {\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\twidth: 1300px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tbackground-image: url(images/admin/bb1.jpg);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator ul {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator li a {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tpadding-top: 4px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 98px;\r\n");
      out.write("\theight: 22px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #336666;\r\n");
      out.write("\tmargin-left: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator li a:hover {\r\n");
      out.write("\tbackground-color: #3d7878;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator ul li ul {\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator ul li:hover ul, #navigator ul a:hover ul {\r\n");
      out.write("\tvisibility: visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\twidth: 1300px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content iframe {\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("\twidth: 1300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth: 1280px;\r\n");
      out.write("\tline-height: 2em;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #336666;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"navigator\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a>商品管理</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminGoods/selectGoods\" target=\"center\">商品详情</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminGoods/toAddGoods\" target=\"center\">添加商品</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminGoods/selectGoods?act=updateSelect\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"center\">修改商品</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminGoods/selectGoods?act=deleteSelect\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"center\">删除商品</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a>类型管理</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminType/selectGoodsType\" target=\"center\">类型详情</a></li> \r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminType/toAddType\" target=\"center\">添加类型</a></li> \r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminType/selectGoodsType?act=deleteSelect\" target=\"center\">删除类型</a></li>   \r\n");
      out.write("\t\t\t\t</ul></li> \r\n");
      out.write("\t\t\t<li><a>用户管理</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminUser/userInfo\" target=\"center\">用户详情</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a>订单管理</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminOrder/orderInfo\" target=\"center\">查询订单</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a>公告管理</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminNotice/toAddNotice\" target=\"center\">添加公告</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminNotice/deleteNoticeSelect\" target=\"center\">删除公告</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href=\"exit\">安全退出</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 框架里原始为所有商品的详情 -->\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<iframe src=\"adminGoods/selectGoods\" name=\"center\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">@湖南理工学院信息学院</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
